"""cycle natural key

Revision ID: 0741eb72f8ee
Revises: b2f33c05b3d0
Create Date: 2026-07-13 09:16:32.215450

"""
from alembic import op
import sqlalchemy as sa


revision = '0741eb72f8ee'
down_revision = 'b2f33c05b3d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cycle_conid_open', 'trade_cycles', ['conid', 'open_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cycle_conid_open', 'trade_cycles', type_='unique')
    # ### end Alembic commands ###
