"""initial schema

Revision ID: b2f33c05b3d0
Revises: 
Create Date: 2026-07-13 08:35:24.263474

"""
from alembic import op
import sqlalchemy as sa


revision = 'b2f33c05b3d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('net_liquidation', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('total_cash', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('gross_position_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('buying_power', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('available_funds', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('excess_liquidity', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('init_margin', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('maint_margin', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('leverage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_ts'), 'account_snapshots', ['ts'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('operator', sa.String(length=4), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=True),
    sa.Column('mime', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('benchmark_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'price_date', name='uq_benchmark_symbol_date')
    )
    op.create_index(op.f('ix_benchmark_prices_price_date'), 'benchmark_prices', ['price_date'], unique=False)
    op.create_index(op.f('ix_benchmark_prices_symbol'), 'benchmark_prices', ['symbol'], unique=False)
    op.create_table('cash_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('settled_cash', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('nlv_in_ccy', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_balances_ts'), 'cash_balances', ['ts'], unique=False)
    op.create_table('daily_equity',
    sa.Column('equity_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('cash', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('stock_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('dividend_accruals', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('interest_accruals', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('deposits', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('withdrawals', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('twr_daily', sa.Numeric(precision=14, scale=10), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_line_hash', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('equity_date')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('rate_to_base', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_date', 'currency', name='uq_fx_date_ccy')
    )
    op.create_index(op.f('ix_fx_rates_rate_date'), 'fx_rates', ['rate_date'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_created_at'), 'insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_insights_kind'), 'insights', ['kind'], unique=False)
    op.create_table('instruments',
    sa.Column('conid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('sec_type', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('classification_source', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('conid')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    op.create_table('journal_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('fields_schema', sa.JSON(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('date_range_from', sa.String(length=10), nullable=True),
    sa.Column('date_range_to', sa.String(length=10), nullable=True),
    sa.Column('records_upserted', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_kind'), 'sync_runs', ['kind'], unique=False)
    op.create_index(op.f('ix_sync_runs_started_at'), 'sync_runs', ['started_at'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_fired_at'), 'alert_events', ['fired_at'], unique=False)
    op.create_index(op.f('ix_alert_events_rule_id'), 'alert_events', ['rule_id'], unique=False)
    op.create_table('cash_transactions',
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('tx_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settle_date', sa.Date(), nullable=True),
    sa.Column('conid', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conid'], ['instruments.conid'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_cash_transactions_conid'), 'cash_transactions', ['conid'], unique=False)
    op.create_index(op.f('ix_cash_transactions_tx_datetime'), 'cash_transactions', ['tx_datetime'], unique=False)
    op.create_index(op.f('ix_cash_transactions_type'), 'cash_transactions', ['type'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('conid', sa.Integer(), nullable=True),
    sa.Column('ratio', sa.String(length=32), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conid'], ['instruments.conid'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_corporate_actions_conid'), 'corporate_actions', ['conid'], unique=False)
    op.create_table('entity_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'entity_type', 'entity_id', name='uq_tag_entity')
    )
    op.create_index(op.f('ix_entity_tags_entity_id'), 'entity_tags', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_tags_tag_id'), 'entity_tags', ['tag_id'], unique=False)
    op.create_table('executions',
    sa.Column('exec_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('perm_id', sa.String(length=32), nullable=True),
    sa.Column('conid', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('trade_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_time_tz', sa.String(length=48), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('order_type', sa.String(length=16), nullable=True),
    sa.Column('commission', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('commission_currency', sa.String(length=8), nullable=True),
    sa.Column('realized_pnl_ib', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conid'], ['instruments.conid'], ),
    sa.PrimaryKeyConstraint('exec_id')
    )
    op.create_index(op.f('ix_executions_conid'), 'executions', ['conid'], unique=False)
    op.create_index(op.f('ix_executions_order_id'), 'executions', ['order_id'], unique=False)
    op.create_index(op.f('ix_executions_perm_id'), 'executions', ['perm_id'], unique=False)
    op.create_index(op.f('ix_executions_trade_time'), 'executions', ['trade_time'], unique=False)
    op.create_table('orders',
    sa.Column('perm_id', sa.String(length=32), nullable=False),
    sa.Column('conid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('order_type', sa.String(length=16), nullable=True),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('aux_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('tif', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('filled', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('remaining', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conid'], ['instruments.conid'], ),
    sa.PrimaryKeyConstraint('perm_id')
    )
    op.create_index(op.f('ix_orders_conid'), 'orders', ['conid'], unique=False)
    op.create_table('positions',
    sa.Column('conid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('daily_pnl', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('price_quality', sa.String(length=16), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conid'], ['instruments.conid'], ),
    sa.PrimaryKeyConstraint('conid')
    )
    op.create_table('trade_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conid', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('fees_total', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('dividends_total', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('matching_method', sa.String(length=16), nullable=False),
    sa.Column('is_manually_adjusted', sa.Boolean(), nullable=False),
    sa.Column('original_matching', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conid'], ['instruments.conid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_cycles_conid'), 'trade_cycles', ['conid'], unique=False)
    op.create_index(op.f('ix_trade_cycles_open_time'), 'trade_cycles', ['open_time'], unique=False)
    op.create_table('cycle_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('exec_id', sa.String(length=64), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['trade_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exec_id'], ['executions.exec_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'exec_id', name='uq_cycle_exec')
    )
    op.create_index(op.f('ix_cycle_executions_cycle_id'), 'cycle_executions', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_cycle_executions_exec_id'), 'cycle_executions', ['exec_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('setup', sa.String(length=64), nullable=True),
    sa.Column('entry_reason', sa.Text(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('catalyst', sa.String(length=256), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('invalidation', sa.Text(), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('planned_rr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_rr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('amount_at_risk', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pct_at_risk', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('emotional_state', sa.String(length=64), nullable=True),
    sa.Column('followed_plan', sa.Boolean(), nullable=True),
    sa.Column('changed_plan_midway', sa.Boolean(), nullable=True),
    sa.Column('mistake', sa.Text(), nullable=True),
    sa.Column('done_right', sa.Text(), nullable=True),
    sa.Column('key_lesson', sa.Text(), nullable=True),
    sa.Column('next_time', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('free_notes', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('extra_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['trade_cycles.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['journal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_cycle_id'), 'journal_entries', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_strategy'), 'journal_entries', ['strategy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_strategy'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_cycle_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_cycle_executions_exec_id'), table_name='cycle_executions')
    op.drop_index(op.f('ix_cycle_executions_cycle_id'), table_name='cycle_executions')
    op.drop_table('cycle_executions')
    op.drop_index(op.f('ix_trade_cycles_open_time'), table_name='trade_cycles')
    op.drop_index(op.f('ix_trade_cycles_conid'), table_name='trade_cycles')
    op.drop_table('trade_cycles')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_conid'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_executions_trade_time'), table_name='executions')
    op.drop_index(op.f('ix_executions_perm_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_order_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_conid'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_entity_tags_tag_id'), table_name='entity_tags')
    op.drop_index(op.f('ix_entity_tags_entity_id'), table_name='entity_tags')
    op.drop_table('entity_tags')
    op.drop_index(op.f('ix_corporate_actions_conid'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_cash_transactions_type'), table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_tx_datetime'), table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_conid'), table_name='cash_transactions')
    op.drop_table('cash_transactions')
    op.drop_index(op.f('ix_alert_events_rule_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_fired_at'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_table('tags')
    op.drop_index(op.f('ix_sync_runs_started_at'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_kind'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_table('settings')
    op.drop_table('journal_templates')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_insights_kind'), table_name='insights')
    op.drop_index(op.f('ix_insights_created_at'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_fx_rates_rate_date'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_table('daily_equity')
    op.drop_index(op.f('ix_cash_balances_ts'), table_name='cash_balances')
    op.drop_table('cash_balances')
    op.drop_index(op.f('ix_benchmark_prices_symbol'), table_name='benchmark_prices')
    op.drop_index(op.f('ix_benchmark_prices_price_date'), table_name='benchmark_prices')
    op.drop_table('benchmark_prices')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_account_snapshots_ts'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
